"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports["default"]=void 0;var _react=_interopRequireDefault(require("react")),_propTypes=_interopRequireDefault(require("prop-types"));function _interopRequireDefault(a){return a&&a.__esModule?a:{default:a}}function _typeof(a){return _typeof="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(a){return typeof a}:function(a){return a&&"function"==typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a},_typeof(a)}function _classCallCheck(a,b){if(!(a instanceof b))throw new TypeError("Cannot call a class as a function")}function _defineProperties(a,b){for(var c,d=0;d<b.length;d++)c=b[d],c.enumerable=c.enumerable||!1,c.configurable=!0,"value"in c&&(c.writable=!0),Object.defineProperty(a,c.key,c)}function _createClass(a,b,c){return b&&_defineProperties(a.prototype,b),c&&_defineProperties(a,c),a}function _possibleConstructorReturn(a,b){return b&&("object"===_typeof(b)||"function"==typeof b)?b:_assertThisInitialized(a)}function _getPrototypeOf(a){return _getPrototypeOf=Object.setPrototypeOf?Object.getPrototypeOf:function(a){return a.__proto__||Object.getPrototypeOf(a)},_getPrototypeOf(a)}function _assertThisInitialized(a){if(void 0===a)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return a}function _inherits(a,b){if("function"!=typeof b&&null!==b)throw new TypeError("Super expression must either be null or a function");a.prototype=Object.create(b&&b.prototype,{constructor:{value:a,writable:!0,configurable:!0}}),b&&_setPrototypeOf(a,b)}function _setPrototypeOf(a,b){return _setPrototypeOf=Object.setPrototypeOf||function(a,b){return a.__proto__=b,a},_setPrototypeOf(a,b)}function _defineProperty(a,b,c){return b in a?Object.defineProperty(a,b,{value:c,enumerable:!0,configurable:!0,writable:!0}):a[b]=c,a}var FakeImg=/*#__PURE__*/function(a){function b(){var a,c;_classCallCheck(this,b);for(var d=arguments.length,e=Array(d),f=0;f<d;f++)e[f]=arguments[f];return c=_possibleConstructorReturn(this,(a=_getPrototypeOf(b)).call.apply(a,[this].concat(e))),_defineProperty(_assertThisInitialized(c),"canvasToUrl",function(){var a=Math.round,b=c.props,d=b.height,e=b.width,f=b.bgColor,g=b.fontColor,h=b.text,i=document.createElement("canvas"),j=i.getContext("2d");i.height=d,i.width=e,j.fillStyle=f,j.fillRect(0,0,e,d);var k=a(e/10),l=h||"".concat(e," x ").concat(d);// Text settings
// Return canvas as data URL
return j.fillStyle=g,j.font="500 ".concat(12>k?12:k,"px sans-serif"),j.textBaseline="middle",j.fillText(l,e/2-j.measureText(l).width/2,d/2),i.toDataURL()}),c}return _inherits(b,a),_createClass(b,[{key:"render",value:function render(){var a=this.props,b=a.alt,c=a.className,d=a.id,e=a.style,f=a.onClick,g=a.onMouseEnter,h=a.onMouseLeave,i={alt:b,src:this.canvasToUrl()};// Create element via React API
return void 0!==c&&(i.className=c),void 0!==d&&(i.id=d),void 0!==f&&(i.onClick=function(){return f()}),void 0!==g&&(i.onMouseEnter=function(){return g()}),void 0!==h&&(i.onMouseLeave=function(){return h()}),_react["default"].createElement("img",i)}}]),b}(_react["default"].Component);FakeImg.propTypes={// alt attribute require in HTML5
alt:_propTypes["default"].string.isRequired,// Background color
bgColor:_propTypes["default"].string,// className if need className attribute
className:_propTypes["default"].string,// Font color
fontColor:_propTypes["default"].string,// height size
height:_propTypes["default"].number.isRequired,// Id
id:_propTypes["default"].string,// text to replace "width x height"
text:_propTypes["default"].string,// css style
style:_propTypes["default"].object,// width size,
width:_propTypes["default"].number.isRequired,// event onClick
onClick:_propTypes["default"].func,// event onMouseEnter
onMouseEnter:_propTypes["default"].func,// event onMouseLeave
onMouseLeave:_propTypes["default"].func},FakeImg.defaultProps={bgColor:"#c19d67",fontColor:"#3a2306"};var _default=FakeImg;exports["default"]=_default;
